---
- name: Common setup for all Kubernetes nodes
  hosts: kubernetes
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - common

- name: Initialize Kubernetes cluster on master
  hosts: master
  become: true
  vars_files:
    - vars/common.yml
    - vars/master.yml
  roles:
    - master

- name: Join worker nodes to the cluster
  hosts: workers
  become: true
  vars_files:
    - vars/common.yml
    - vars/worker.yml
  roles:
    - worker

- name: Install NGINX Ingress Controller
  hosts: master
  become: true
  become_user: ubuntu
  gather_facts: true
  vars_files:
    - vars/common.yml
    - vars/master.yml
  roles:
    - ingress
